from .main_api import main_api_bp, main_api_entities
from .orders_manager_api import orders_manager_api_bp, orders_manager_api_entities
from .products_manager_api import products_manager_api_bp, products_manager_api_entities